### PR TITLE
Add Finnish translation

### PR DESCRIPTION
**Pull request by Jollailija**
Greetings @nesnomis !

I read on the Jolla Store that your app is almost perfect for Finnish listeners- this PR should help bridge the gap to absolute perfection :)

Cheers,
jollailija

### CODE REVIEW

**Comment by Jollailija** [comment]
Needs more work, do not merge yet

**Comment by Jollailija** [comment]
I'd say the translation is production ready, but I'm unable to test it on device. The existing Swedish translation didn't work either, so I guess it's nothing specific to this translation and thus I deem this PR mergeable.

**Comment by eson57** [comment]
>The existing Swedish translation didn't work either, so I guess it's nothing specific to this translation and thus I deem this PR mergeable.

Swedish translation works just fine for me. There's an parse error in your Finnish translation file, maybe that's why it didn't work. Cant find the time to investigate further.  ;)

`Parse error at harbour-allradio-fi.ts:2259:30: Expected '#' or '[a-zA-Z]', but got ' '.`

**Comment by Jollailija** [comment]
Hi Eson, nice to see you're still active all these years later!

Thanks for the pointer, there appears to be an unescaped `&`. Guess I'll have to pay closer attention to the build logs, shame on me

**Comment by Jollailija** [comment]
`Updating '/home/user/temp/build-harbour-allradio-SailfishOS_3_4_0_24_armv7hl_in_sailfish_os_build_engine-Release/translations/harbour-allradio-fi.qm'...
    Generated 521 translation(s) (521 finished and 0 unfinished)`
    
No parse errors this time, yet no Finnish text shows up... Let me repull and rebuild once more

**Comment by Jollailija** [comment]
Here's the full build log from a fresh pull: https://gist.github.com/Jollailija/a7e12881f52346155124e024a5eeb956
@eson57 could you do me the small favor of replacing the Swedish translation file with the Finnish one and building it to see if the text shows up? If it does, the problem's on my end and not in the translation/code.

**Comment by eson57** [comment]
Running `LANG=fi-FI harbour-allradio` gives me English interface. It's the same with all available locale. Normal launch from grid gives me Swedish interface.
Replacing sv with fi gives a beautiful Finnish GUI when launching from grid.  ;)

**Comment by eson57** [comment]
See my edit above please.

**Comment by Jollailija** [comment]
Wait what, I'm confused. My LANG is by default fi_FI.utf8, setting it manually to fi works and sv_SE gives me Swedish. What is it supposed to be?

**Comment by eson57** [comment]
File names have always been sv/fi/de and so on, for this app.
hmm.. I see now the code is in ts file is `<TS version="2.1" language="sv_SE" sourcelanguage="en">`

**Comment by Jollailija** [comment]
I've tried these so far:

`<TS version="2.1" language="fi" sourcelanguage="en">`
`<TS version="2.1" language="fi_FI" sourcelanguage="en">`
`<TS version="2.1" language="fi-FI" sourcelanguage="en">`
`<TS version="2.1" language="fi_FI.utf8" sourcelanguage="en">`

Setting the LANG manually works with any of these so I was able to go through and make sure the translations are all extra fine and context aware. I don't see how merging this would hurt, so I'll remove the [DNM]. Maybe the problem is with my phone, but then again harbour-scoreboard's translations work fine. I'll have to look more into this later.

**Comment by Jollailija** [comment]
Switching my phone's language to "Svenska" from the Settings sets LANG to `sv_SE.utf8` and the Swedish translation is shown. Switching back to "Suomi" sets LANG to `fi_FI.utf8` and now the Finnish translation is shown. Maybe I just hallucinated vividly, but I could swear it didn't work before. Anyhow: the translation is now very much functional and ready for inclusion. Thanks for your help and happy holidays @eson57 !

**Comment by eson57** [comment]
I had some trouble my self getting the app back to Swedish, so maybe it's just a bit unstable. What do I know. I'm not even a real programmer. Happy holiday to you to @Jollailija !

**Pull request merged**
